### ISSUE TITLE
Add referencedBy endpoint

### ISSUE THREAD

**Issue by hackaugusto** [Aiven-Open/karapace#197]
`GET /subjects/(string: subject)/versions/{versionId: version}/referencedby`, this depends on https://github.com/aiven/karapace/issues/195

Docs on schema registry: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--subjects-(string-%20subject)-versions-versionId-%20version-referencedby

**Comment by tvainika** [comment]
Support for this has been added in #560
