### ISSUE TITLE
test_master_coordinator.py::test_master_selection is flaky

### ISSUE THREAD

**Issue by juha-aiven** [Aiven-Open/karapace#218]
# What happened?

Tests failing when running Test Suite (Python 3.7) for https://github.com/aiven/karapace/pull/216. Details in the attached file [logs_2793.zip](https://github.com/aiven/karapace/files/6456939/logs_2793.zip).

# What did you expect to happen?

Tests pass, no code changes in the PR.

# What else do we need to know?

Include your platform, version, and any other information that seems relevant.

**Comment by tvainika** [comment]
This test is working nowaways just fine.
