### ISSUE TITLE
KafkaConnectionError: Socket EVENT_READ without in-flight-requests on debian 10 with python 3.9

### ISSUE THREAD

**Issue by vutdv-ic** [Aiven-Open/karapace#336]
# Running REST Proxy on debian10 with python3.9 encounter following error

> Feb 10 02:21:34 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=3 host=yy.yy.yy.yy:9094 <connecting> [IPv4 ('yy.yy.yy.yy', 9094)]>: connecting to yy.yy.yy.yy:9094 [('yy.yy.yy.yy', 9094) IPv4]
Feb 10 02:21:34 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <connecting> [IPv4 ('xx.xx.xx.xx', 9094)]>: connecting to xx.xx.xx.xx:9094 [('xx.xx.xx.xx', 9094) IPv4]
Feb 10 02:21:34 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <handshake> [IPv4 ('xx.xx.xx.xx', 9094)]>: Loading SSL CA from /opt/karapace-rest-proxy/etc/karapace-rest-proxy/cafile.pem
Feb 10 02:21:34 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <handshake> [IPv4 ('xx.xx.xx.xx', 9094)]>: Loading SSL Cert from /opt/karapace-rest-proxy/etc/karapace-rest-proxy/cacert.crt
Feb 10 02:21:34 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <handshake> [IPv4 ('xx.xx.xx.xx', 9094)]>: Loading SSL Key from /opt/karapace-rest-proxy/etc/karapace-rest-proxy/cakey.key
Feb 10 02:21:35 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <handshake> [IPv4 ('xx.xx.xx.xx', 9094)]>: Connection complete.
Feb 10 02:21:35 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=3 host=yy.yy.yy.yy:9094 <handshake> [IPv4 ('yy.yy.yy.yy', 9094)]>: Connection complete.
Feb 10 02:21:35 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=bootstrap-0 host=xx.xx.xx.xx:9094 <connected> [IPv4 ('xx.xx.xx.xx', 9094)]>: Closing connection.
Feb 10 02:21:35 ip-rest-proxy karapace-rest-proxy[2039]: kafka.conn                  MainThread        INFO            <BrokerConnection node_id=3 host=yy.yy.yy.yy:9094 <connected> [IPv4 ('yy.yy.yy.yy', 9094)]>: Closing connection. KafkaConnectionError: Socket EVENT_READ without in-flight-requests
Feb 10 02:21:35 ip-rest-proxy karapace-rest-proxy[2039]: kafka.client                MainThread        WARNING         Node 3 connection failed -- refreshing metadata

# What going on

The node is not stable.
On start up, we can making call to the api normally, but when metadata client expired (metadata_max_age_ms), it reconnecting fail and keep trying. While that happen, the node become unavailable.

The REST Proxy working fine on debian9 with python3.8

**Comment by hackaugusto** [comment]
Hi @vutdv-ic, thank you for the report. The first thing we would need is a way to reproduce the issue, for that I need additional details on your environment / usage pattern.

- What is your setup?
   - Are you using docker, running locally on your machine, using a vm?
- What are the steps required to reproduce the issue?

**Comment by vutdv-ic** [comment]
Hi @hackaugusto,

The setup:
We run Karapace REST Proxy in a container with base image is debian10 with python3.9 install.
REST Proxy connect to Kafka via SSL connection (you can see that in the log)

Behavior:
- When the REST Proxy up
- We do a curl call such as listing broker
- Expected result response from REST Proxy
- Then wait for a moment (depend on metadata_max_age_ms)
- Make another same call to REST Proxy
- Timeout will happen and check for the log in REST Proxy

**Comment by hackaugusto** [comment]
@vutdv-ic , we are currently packaging using [debian:stable-slim](https://github.com/aiven/karapace/blob/e0c78877dbe178c1e945f76b5295b15232a39a70/container/Dockerfile#L3) as the base image:

```
karapace@f7f4736de5e2:/opt/karapace$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
karapace@f7f4736de5e2:/opt/karapace$ python3 --version
Python 3.9.2
```

For me to debug the issue you're experiencing I need the `Dockerfile` or the base image.

---

As a side note, did you try updating your debian base image to bullseye or use the container [image we are releasing](https://github.com/aiven/karapace/pkgs/container/karapace)? I didn't experience the issue you reported with the image we are releasing:

```
karapace$ docker-compose -f container/docker-compose.yml up -d
karapace$ curl 'http://localhost:8082/brokers
karapace$ sleep 15
karapace$ curl 'http://localhost:8082/brokers
```

**Comment by vutdv-ic** [comment]
here the docker files:
base-image: debian:10-slim
adding python: [base-python-dockerfile.txt](https://github.com/aiven/karapace/files/8182859/base-python-dockerfile.txt)
m
adding karapace: [karapace.docker.txt](https://github.com/aiven/karapace/files/8182862/karapace.docker.txt)
 start.sh just only start rest proxy with a custom rest.json.config file.

**Comment by jjaakola-aiven** [comment]
REST Proxy uses different library and this issue as is won't be fixed.
