### ISSUE TITLE
Copyright check depends on very recent version of git

### ISSUE THREAD

**Issue by aiven-anton** [Aiven-Open/karapace#563]
### What happened?

The copyright check breaks locally for a contributor with:

```
$ git grep -ELm1 'Copyright (c) 20[0-9]{2} Aiven' -- '.py' ':!init.py'
error: unknown switch `m'
```

https://github.com/aiven/karapace/pull/560#issuecomment-1469001219

Interestingly this results in a false negative check.

### What did you expect to happen?

Check failing.

### What else do we need to know?

It looks like the `-m` switch only [added last year](https://github.com/git/git/pull/1278). I think many developers use system-installed git which tend to not be latest version. I think we should leave a little more leeway in terms of git versions supported.

**Comment by libretto** [comment]
MacOS issue: 

(py39) serge@Sergiys-MacBook-Pro-2 karapace_mainstream % git grep -ELm1 'Copyright (c) 20[0-9]{2} Aiven' -- '.py' ':!init.py'
error: unknown switch `m'

**Comment by aiven-anton** [comment]
@libretto The fix was merged already, can you sync with main and see if you still have an issue? The updated code no longer uses git grep.

**Comment by libretto** [comment]
@aiven-anton Now lint in Python 3.11 environment works for me on macOS and Debian 11.

**Comment by aiven-anton** [comment]
@libretto Great 👍
