### ISSUE TITLE
Use aiokafka in rest proxy code

### ISSUE THREAD

**Issue by gabriel-tincu** [Aiven-Open/karapace#60]
Related to https://github.com/aiven/karapace/issues/30. All that's needed is switching consumers with async consumers. Admin client can remain the same until there's an async one in sight

Edit:
As of 2.01 ( 40c557fe47e285638f3e7bf401a73df046d96ea4 ) the consumers and producers are using aiokafka. The missing piece is the admin interface. It is an open question if the admin interface is a priority for the aiokafka project https://github.com/aio-libs/aiokafka/issues/623 , https://github.com/aio-libs/aiokafka/issues/665#issuecomment-711068802 https://github.com/aio-libs/aiokafka/pull/639

**Comment by jjaakola-aiven** [comment]
Obsolete, the REST proxy uses `confluent-kafka-python`.
