### ISSUE TITLE
handle os signals (gracefully)

### ISSUE THREAD

**Issue by gabriel-tincu** [Aiven-Open/karapace#72]
at the moment we do not really do anything on SIGHUP or SIGTERM, and only react to SIGKILL. 
Investigate feasibility of implementing logic for config reload and graceful shutdown
The former is iffy but the latter should be pretty straight forward. Entry point would be `karapace/karapace_all.py`

**Comment by hackaugusto** [comment]
`SIGINT` and `SIGTERM` are handled by default:

https://github.com/aio-libs/aiohttp/blob/fa8adadc1a84333434431778d3da59d7dbed8161/aiohttp/web_runner.py#L269-L270

https://github.com/aio-libs/aiohttp/blob/v3.7.1/aiohttp/web.py#L474

This should be sufficient for a clean shut-down as long as there are no web-sockets:

https://docs.aiohttp.org/en/stable/web_advanced.html#graceful-shutdown

**Comment by hackaugusto** [comment]
Configuration reload seems a bit tricky, ATM the configuration file determines which URLs will be available:

https://github.com/aiven/karapace/blob/b27a58c5f9874accd0b330ac840cdcd63b7de2ff/karapace/karapace_all.py#L54-L62

Is it fine if both services are always enabled?

**Comment by jjaakola-aiven** [comment]
For now there is no plans to support hot reloading.
