### ISSUE TITLE
Failure when producing events with the latest version 3.7.3

### ISSUE THREAD

**Issue by MSdracanovic** [Aiven-Open/karapace#724]
Hello,
We are using Aiven Karapace REST API to publish event from our ERP to other entities in our company.
Recently with automatic maintenance update we got update from version 3.6.2 to version 3.7.3

After update we can produce any event from our system

error that we are receiving is

`{
    "error_code": 42205,
    "message": "Invalid schema. format = AVRO, schema_id = 7"
}`

We tested with simple example and got same result
schema
`{
  "fields": [
    {
      "name": "age",
      "type": "int"
    }
  ],
  "name": "Obj",
  "type": "record"
}`

payload 
`{
   "value_schema_id": 7,
   "records":[
      {
         "value":{
            "age":55
         }
      }
   ]
}`

Current Content-Type in header is `application/vnd.kafka.avro.v2+json`
When we change to `application/vnd.kafka.json.v2+json` we can produce message but our consumers can not consume it.

We want to avoid downgrade and to solve this issue.
Do you have any proposal on this.

Thanks in Advance

**Comment by tvainika** [comment]
We have identified that in pull request #664 was additional validation with schema registered under matching subject, which was not fully backward compatible. This change was published with Karapace 3.7.0 in July.

If you are Aiven customer, please contact via Aiven support to get your services mitigation for this issue.

Our long term plan is to add configuration toggle for schema registered under a subject to validate the content when producing to a topic. But this can take some days to became available with next Karapace release.

**Comment by MSdracanovic** [comment]
Thank for quick response.
After  we recreate schema with format name  topicname-value and topicname-key we manage to produce events.
