### ISSUE TITLE
KafkaConfigurationError: Unrecognized configs: {'kafka_client'}

### ISSUE THREAD

**Issue by lkfox993** [Aiven-Open/karapace#776]
# What happened?

I have error when i build karapace from source and run in docker container. the error is: https://github.com/Aiven-Open/karapace/blob/6cb38112d3f8d1ff5eb2a61fef1bedab6bc21768/karapace/schema_reader.py#L188

# What did you expect to happen?

I expected everything to start the same way as with the finished image ghcr.io/aiven/karapace:latest

# What else do we need to know?

you pass kafka_client in KafkaConsumer https://github.com/Aiven-Open/karapace/blob/6cb38112d3f8d1ff5eb2a61fef1bedab6bc21768/karapace/schema_reader.py#L90 but in source code kafka consumer [consumer source](https://kafka-python.readthedocs.io/en/master/_modules/kafka/consumer/group.html) we have a check ` 
def __init__(self, *topics, **configs):
        # Only check for extra config keys in top-level class
        extra_configs = set(configs).difference(self.DEFAULT_CONFIG)
        if extra_configs:
            raise KafkaConfigurationError("Unrecognized configs: %s" % (extra_configs,))
`

I think that's the problem because in default_config kafka consumer we doesnt have kafka_client param

Thank you for your contribution to karapace

**Comment by aiven-anton** [comment]
@lkfox993 Could you please provide the full log of the error, including including the traceback if there is one?

**Comment by aiven-anton** [comment]
@lkfox993 I suspect you don't have the correct version of kafka-python installed, note that only the requirements specified in https://github.com/Aiven-Open/karapace/blob/main/requirements/requirements.txt are supported and tested.

**Comment by aiven-anton** [comment]
I'll close this for now, please feel free to follow-up if more information surfaces.

For reference you can look at the Dockerfile used for the image we publish as `ghcr.io/aiven/karapace`:

- https://github.com/Aiven-Open/karapace/blob/da85083b960c4a15e63705db690e9659dfa8a954/container/Dockerfile
