### ISSUE TITLE
Karapace version

### ISSUE THREAD

**Issue by techkuz** [Aiven-Open/karapace#948]
# What can we help you with?

Is there a way to know via request which karapace version is server using?

# Where would you expect to find this information?

In documentation

**Comment by eliax1996** [comment]
Hi!
If you look the `health` endpoint it returns as part of the reply the version of Karapace.
You can take a look [here](https://github.com/Aiven-Open/karapace/blob/ad872d4c9d576aeeaca7d110a45d798e2f0da47e/karapace/karapace.py#L93)
